---
- name: network device backup to git
  hosts: all
  gather_facts: false
  vars:
    # Setting this to true here or overriding it in a playbook will cause the run to
    # check if it can ping a host before attempting to back it up.  This will speed up
    # overall processing of the play(with large hosts).
    check_for_reachability: True

  tasks:
    # Run this code block when checking for reliability
    - name: check for reachability block
      when: check_for_reachability
      block:
        - name: Ping for reachability
          command: ping -c1 {{ ansible_host }}
          delegate_to: localhost
          register: ping_result
          ignore_errors: true

        - name: Group hosts by online
          group_by: key=reachable
          when: ping_result.rc == 0

    # Reliability was skipped
    - name: not checking for reachability
      group_by: key=reachable
      when: not check_for_reachability

- name: network device backup to git
  hosts: reachable
  gather_facts: false
  connection: network_cli
  vars:
    backup_dir: "{{ playbook_dir }}/net_backups"
    backup_file: "{{ backup_dir }}/{{ inventory_hostname }}"

  tasks:

  - import_role:
      name: network_backup_git
